### ISSUE TITLE
[FEATURE] Add exceptions for Tuesdays and Thursdays

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/WednesdayBot#3]
As suggested by @guieiras:
> I thought a feature like:
> 
> On Tuesday,
> "Is it Wednesday?" returns "Keep calm and wait for Wednesday" or "Brace yourself, Wednesday is coming" ?
> 
> On Thursday,
> "Is it Wednesday?" returns "It was yesterday. Do you want more Wednesdays? Me too"
> 
> May I try to do it?

**Comment by guieiras-dev** [comment]
Thank You!
