### ISSUE TITLE
[FEATURE] EmbedMessage workaround

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/WednesdayBot#6]
I've been loving the bot so far. However, the yellow on the messages is a little bit disruptive

![image](https://user-images.githubusercontent.com/19593836/96367460-53f51e80-1124-11eb-98c1-3ba88bb576b0.png)

Think you can make that notification better? Thinking outside the box will be greatly welcome

**Comment by adamllwilliams** [comment]
Hey, is it ok if I pick this up?

**Comment by tomassiriouala** [comment]
Sure!
